name: Ruby

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.4.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      
      - name: Run tests
        run: bundle exec rake

      - name: Build gem
        run: gem build orion.gemspec
